In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/stocks.csv", header=[0, 1], index_col=0)
df

Ticker                           NFLX
Price                            Open        High         Low       Close
Date
2014-01-02 00:00:00+00:00   52.401428   52.511429   51.542858   51.831429  \
2014-01-03 00:00:00+00:00   52.000000   52.495712   51.842857   51.871429
2014-01-06 00:00:00+00:00   51.889999   52.044285   50.475716   51.367142
2014-01-07 00:00:00+00:00   49.684284   49.698570   48.152859   48.500000
2014-01-08 00:00:00+00:00   48.104286   49.425713   48.074287   48.712856
...                               ...         ...         ...         ...
2024-11-07 00:00:00+00:00  781.369995  798.219971  779.940002  796.539978
2024-11-08 00:00:00+00:00  797.359985  799.059998  788.650024  795.039978
2024-11-11 00:00:00+00:00  795.900024  806.820007  795.570007  805.440002
2024-11-12 00:00:00+00:00  807.500000  820.369995  803.750000  819.500000
2024-11-13 00:00:00+00:00  822.619995  836.989990  820.539978  830.469971

Ticker                                                SONY
Price                       Adj Close    Volume       Open       High
Date
2014-01-02 00:00:00+00:00   51.831429  12325600   3.466000   3.478000  \
2014-01-03 00:00:00+00:00   51.871429  10817100   3.442000   3.452000
2014-01-06 00:00:00+00:00   51.367142  15501500   3.460000   3.498000
2014-01-07 00:00:00+00:00   48.500000  36167600   3.472000   3.476000
2014-01-08 00:00:00+00:00   48.712856  20001100   3.480000   3.664000
...                               ...       ...        ...        ...
2024-11-07 00:00:00+00:00  796.539978   3295100  18.200001  18.340000
2024-11-08 00:00:00+00:00  795.039978   1910600  19.500000  20.670000
2024-11-11 00:00:00+00:00  805.440002   2399200  19.340000  19.400000
2024-11-12 00:00:00+00:00  819.500000   2814100  19.000000  19.010000
2024-11-13 00:00:00+00:00  830.469971   2763700  18.690001  18.709999

Ticker                                           ...      SQNXF
Price                            Low      Close  ...        Low      Close
Date                                             ...
2014-01-02 00:00:00+00:00   3.416000   3.432000  ...  17.629999  17.629999  \
2014-01-03 00:00:00+00:00   3.424000   3.436000  ...  17.629999  17.629999
2014-01-06 00:00:00+00:00   3.454000   3.460000  ...  17.740000  17.809999
2014-01-07 00:00:00+00:00   3.440000   3.464000  ...  17.809999  17.809999
2014-01-08 00:00:00+00:00   3.452000   3.650000  ...  17.809999  17.809999
...                              ...        ...  ...        ...        ...
2024-11-07 00:00:00+00:00  18.120001  18.270000  ...  37.500000  37.500000
2024-11-08 00:00:00+00:00  19.500000  19.910000  ...  37.590000  37.590000
2024-11-11 00:00:00+00:00  18.889999  19.120001  ...  33.959999  33.959999
2024-11-12 00:00:00+00:00  18.620001  18.670000  ...  33.959999  33.959999
2024-11-13 00:00:00+00:00  18.440001  18.500000  ...  37.049999  37.049999

Ticker                                        NTDOY
Price                      Adj Close Volume    Open    High     Low   Close
Date
2014-01-02 00:00:00+00:00  15.835082      0   3.324   3.356   3.310   3.310  \
2014-01-03 00:00:00+00:00  15.835082      0   3.358   3.358   3.298   3.324
2014-01-06 00:00:00+00:00  15.996759    300   3.384   3.404   3.376   3.402
2014-01-07 00:00:00+00:00  15.996759      0   3.410   3.440   3.410   3.430
2014-01-08 00:00:00+00:00  15.996759      0   3.772   3.780   3.724   3.732
...                              ...    ...     ...     ...     ...     ...
2024-11-07 00:00:00+00:00  37.500000      0  13.330  13.560  13.190  13.500
2024-11-08 00:00:00+00:00  37.590000  10900  13.500  13.500  13.230  13.370
2024-11-11 00:00:00+00:00  33.959999    700  13.420  13.500  13.370  13.400
2024-11-12 00:00:00+00:00  33.959999      0  13.500  13.500  13.360  13.480
2024-11-13 00:00:00+00:00  37.049999    200  13.110  13.160  12.950  13.000

Ticker
Price                     Adj Close   Volume
Date
2014-01-02 00:00:00+00:00     3.310   160500
2014-01-03 00:00:00+00:00     3.324   120000
2014-01-06 00:00:00+00:00     3.402   354500
2014-01-07 00:00:00+00:00     3.430   153000
2014-01-08 00:00:00+00:00     3.732   696500
...                             ...      ...
2024-11-07 00:00:00+00:00    13.500  2303100
2024-11-08 00:00:00+00:00    13.370   835700
2024-11-11 00:00:00+00:00    13.400   855700
2024-11-12 00:00:00+00:00    13.480   616000
2024-11-13 00:00:00+00:00    13.000   830000

[2736 rows x 30 columns]